### ISSUE TITLE
Add prop/callback like onListen but for specific times

### ISSUE THREAD

**Issue by matheusfillipe** [lhz516/react-h5-audio-player#101]
I have a little project where I a have this audio player and I have to highlight and scroll to the words it is saying in real time. I tried low listenInterval but I think there might be a browser limitation for this and it is jumping some words, which means, there is a limit for how slow listenInterval can be.

I was thinking, is it possible to implement a specific callback or assign each of the times to be triggered? and only then they do something. Because the interval between words in a normal text is very short. Well I am open for any ideas of how to address that problem.

**Comment by lhz516** [comment]
It's hard if want to do it word by word because sometimes the gap between two words are even shorter than `onListen` event with 0 interval. Maybe you want to combine some words together, and also convert them to approximate values. Assume you have a list of times such as `timeStamps = [0.233, 12.3233, 16.988, 35.001]`. You may want to get the approximate values and check with the approximate value of  `audio.currentTime`.

For example:
```js
stamps = timeStamps.map(item => Math.round(item))

handleListen = (e) => {
  if (stamps.includes(Math.round(e.target.currentTime))) {
    // do something
  }
}
```
If `Math.round` is too inaccurate for you, you may also try `toFix(1)` or `(2)` on the numbers
