### ISSUE TITLE
Styling with tailwindcss

### ISSUE THREAD

**Issue by thefilmmaking** [lhz516/react-h5-audio-player#142]
I'm having trouble getting the custom styling using tailwindcss in my react app. It would've been preferable if the library allowed props to tap into/replace atleast the major classes such as the controls-section for example. It's difficult simply modifying almost any css besides the`.rhap_container`. Even inheriting custom css classes isn't overwriting the existing styles such as` .rhap_controls-section` (trying to modify the margin around the play button for example). Is there a recommended workflow for getting it to gel well with a library like tailwindcss? Or a possible feature request to allow props to change atleast the major css sections via props (i.e.` rhapContainerClass={}`). Thanks,

**Comment by lhz516** [comment]
The existing css classes can definitely be overwritten. If you are talking about `.rhap_controls-section`, it's because the selector needs to be more specific. In this case, [.rhap_controls-section](https://github.com/lhz516/react-h5-audio-player/blob/master/src/styles.scss#L42) is nested under `.rhap_stacked`. You need to add the parent selector to overwrite:
```scss
.rhap_stacked .rhap_controls-section {
  // margin-top: 12px;
}
```
