### ISSUE TITLE
Audio doesn't play with Vite in dev mode with HMR

### ISSUE THREAD

**Issue by alexkuc** [lhz516/react-h5-audio-player#166]
I am using React+TypeScript with this plugin with [Vite](https://vitejs.dev/) for my frontend tooling. When running in dev mode (with HMR), audio doesn't play. I don't get any errors or any other indicators, it just doesn't work. When using `preview` or `build` mode, everything works fine.

I have made a repo to replicate the issue: https://github.com/alexkuc/react-h5-audio-player-bug

Please let me know if you need help with Vite or how I can do further debugging. This is a really cool plugin!

**Comment by lhz516** [comment]
Do you have the same issue as https://github.com/lhz516/react-h5-audio-player/issues/162 ?

**Comment by alexkuc** [comment]
@lhz516 I am not using Nextjs. But that issue could overlap with mine? That's actually the reason I made a separate issue since I _don't_ use Nextjs.

**Comment by lhz516** [comment]
I ran your repo in my local and was able to reproduce the issue. I'm very confused because the player lib passes the `src` directly from `props` to the `audio` element, see the code here: https://github.com/lhz516/react-h5-audio-player/blob/9a7d62277bc043ebebac23fc349a129b93d9da04/src/index.tsx#L744

But we get no `src` attribute while `yarn dev`
![image](https://user-images.githubusercontent.com/9879279/186830107-49235499-dd42-4d87-a56f-5381aa539446.png)

I'm still investigating it, maybe it's due to the vite dev build system issue. The good news is that prod version is fine.

**Comment by lhz516** [comment]
Okay, I know the root cause now. 

In `componentWillUnmount`, there is `audio.removeAttribute('src') `.
https://github.com/lhz516/react-h5-audio-player/blob/9a7d62277bc043ebebac23fc349a129b93d9da04/src/index.tsx#L701

Your framework unexpectedly ran this lifecycle even if the component is not being destroyed.

We need to do `audio.removeAttribute('src')` and `audio.load()` in `componentWillUnmount` because we need the audio to stop playing when the component is removed from the DOM.

Please open an issue in Vite repo.

**Comment by alexkuc** [comment]
@lhz516 

> Your framework unexpectedly ran this lifecycle even if the component is not being destroyed.

You mean Vite keeps running `componentWillUnmount` during `dev`, which is what breaks the player, right?

**Comment by lhz516** [comment]
@alexkuc Correct. It works fine in prod, but only got this issue in dev.

**Comment by alexkuc** [comment]
@lhz516 To be honest, I don't have too much free time right now. And I don't have much experience with class-based components. In this case, should I close this issue? Or should I keep it open in case someone else runs into the same issue?

**Comment by lhz516** [comment]
It's actually a non-blocking issue since it works in production env. Feel free to close.
