### ISSUE TITLE
showing infinity 

### ISSUE THREAD

**Issue by abidhkm** [lhz516/react-h5-audio-player#19]
![Screenshot from 2019-12-12 12-46-30](https://user-images.githubusercontent.com/22368311/70696762-c19f1580-1cdd-11ea-8b9a-b199d25e2b45.png)
it is displaying infinity and Nan 
why it is happening ?
once we played it, next time onwards works fine.. only first time plays this happens

**Comment by abidhkm** [comment]
it is working fine in firefox
the problem is in chrome

**Comment by lhz516** [comment]
This library uses `Math.floor(duration / 60)` to calculate duration minutes, and `Math.floor(duration % 60)` for duration seconds.

It's unlikely to get `Infinity` and `NaN` unless your audio duration is `Infinity`

![image](https://user-images.githubusercontent.com/9879279/70772027-136c8d80-1d28-11ea-9e43-d2f888f19aca.png)

There are some results if you google "html audio duration infinity". It's probably because of the server responded header of your audio file. Could you take a look?

**Comment by lhz516** [comment]
It is fixed in 2.x. Closing

**Comment by abidhkm** [comment]
this is the exact problem I am facing
https://github.com/mdn/web-dictaphone/issues/9
it's not a problem with this library I think
