### ISSUE TITLE
Fast Forward and Backward audio on button click

### ISSUE THREAD

**Issue by anshulagarwal92** [lhz516/react-h5-audio-player#2]
Hello @lhz516 ,

I really like this player - nice and customizable.

I would like to request a new feature to fast forward and backward an audio, so that when forward/backward buttons are clicked it can be forwarded and backward up-to particular time interval.

**Comment by lhz516** [comment]
Thanks for the suggestion. I did research on different music players and I found that very few of them are still use fast forward/backward button. Instead, they are using next/previous song button, like this (Spotify):
![image](https://user-images.githubusercontent.com/9879279/56857060-6de1e680-691d-11e9-8ae1-81f9d648df2d.png)

Instead of adding fast forward/backward button, I'm proposing to add some keyboard events on it. For example, Left arrow key for 5 sec backward, Right arrow key for 5 sec forward.
