### ISSUE TITLE
Adding HTML to <AudioPlayer />

### ISSUE THREAD

**Issue by anonet1** [lhz516/react-h5-audio-player#25]
Hi there,

If I want to add icon, text inside AudioPlayer, is there a way to do this?

**Comment by lhz516** [comment]
Do you mean something like an extra custom button next to the "loop" button?

**Comment by anetk** [comment]
Yes. And some extra custom text above play.

**Comment by lhz516** [comment]
I've been thinking about customization since long time ago. Adding some props like `header` and `footer` is easy, but how to organize the panels under the progress bar is a big question.

There's a built-in Loop button there, if we only have a prop called `leftPanel`, what if we want some buttons on both left and right sides of Loop button? What if some more built-in buttons are added? Can we reorder the built-in buttons with custom buttons?

I think I will add `header` and `footer` props first, and need more time to think about custom panels under progressbar. Please feel free to share your thoughts as well.

**Comment by anetk** [comment]
Another thing also - how would I change SVGs for my custom icons (play, arrows, etc). The only idea I have would be to hide with css and add new ones as pseudo elements.

**Comment by lhz516** [comment]
For custom icons, it's been discussed here https://github.com/lhz516/react-h5-audio-player/issues/24

This is a very straight forward feature which will be added soon.

**Comment by anetk** [comment]
I was able to do it with CSS - I did diplay:none on the svg and applied my icon on the button as background-image. 

Do you have ideas on how to have different color for the filled area of the progress bar?

**Comment by lhz516** [comment]
There's sass/less variable `$rhap_bar-color` to overwrite bar color. You can also overwrite `.rhap_progress-bar`'s `background-color`/`background-image` if you don't want to affect volume bar.

I'll probably separate progress and volume bar colors to two sass/less variables.

**Comment by anetk** [comment]
That's for the whole bar though. 
I'm trying to change color only for the filled area. 
<img width="216" alt="Screen Shot 2020-02-26 at 11 50 13" src="https://user-images.githubusercontent.com/11873129/75386028-cb282a80-5895-11ea-8c47-f82949ac7333.png">

**Comment by lhz516** [comment]
Ah, I got what you said, but this is what I see more often:
![image](https://user-images.githubusercontent.com/9879279/75396692-fd438780-58a9-11ea-9dbb-e3be18fb4c89.png)
I think even there's color on filled area, we still need that circle indicator, otherwise it will have conflict against the download progress feature.

**Comment by anonet1** [comment]
Yes that's exactly what I need. I didn't see this on your demo. So I can use rhap_progress-bar for this?

**Comment by lhz516** [comment]
Yea, you are right. I searched some audio player UI, the seeked progress is usually filled with color. I'll add this and make it be controlled by a prop.

**Comment by lhz516** [comment]
Released `2.4.0` https://github.com/lhz516/react-h5-audio-player/releases/tag/v2.4.0

More customization options are on the way
