### ISSUE TITLE
[Feature Request] Would like to have current time in reverse.

### ISSUE THREAD

**Issue by joseph1125** [lhz516/react-h5-audio-player#31]
First of all, thank you for the amazing library, I would like to ask for a UI feature to be able to show current time as (total time - current played time). For example, the audio is 2 min long, and then it is already played for 30 seconds, it should show "1:30"

**Comment by lhz516** [comment]
There are definitely some use cases like this. Here's a solution you can try:

Since you can [access the audio ref](https://github.com/lhz516/react-h5-audio-player#access-to-the-audio-element), you can write a util function `getDisplayTime(audio.duration - audio.currentTime)`, and use `customProgressBarSection` prop to overwite the existing layout. 

Maybe I can export [getDisplayTimeBySeconds](https://github.com/lhz516/react-h5-audio-player/blob/5f56a148fb6fd469f3efad47101babe619697f81/src/utils.ts#L32) util for developers to use.

**Comment by joseph1125** [comment]
I did implement a custom component similar to your method, but what I don't like about this method is that I have to maintain states of the current time and the duration of the audio.

**Comment by lhz516** [comment]
For implementing it inside the library, I don't have a best solution on top of my mind. Maybe we can add another built-in UI module called `RHAP_UI.CURRENT_LEFT_TIME`. Let me know if you have any better ideas.

**Comment by joseph1125** [comment]
I think adding another UI module would be more sensible

**Comment by lhz516** [comment]
Published 3.0.2, added UI module `RHAP_UI.CURRENT_LEFT_TIME`

Example: https://static.hanzluo.com/react-h5-audio-player-storybook/index.html?path=/docs/layouts-advanced--use-current-left-time

**Comment by joseph1125** [comment]
Tried and it is working flawlessly, thank you very much
