### ISSUE TITLE
Support responsive layout for width < 300px

### ISSUE THREAD

**Issue by JeffreyCA** [lhz516/react-h5-audio-player#37]
I want to request supporting alternative layouts where the audio player cannot fit. Right now the width of the player is capped to 300px, even if its parent element may be smaller. This can cause it to look weird especially on smaller screens.

A related request, can you look into supporting a bare minimal layout, where the audio player is simply a Play/Stop button? No seek bar, no timestamps, no pause, no volume, etc. Press to play, press again to stop the player and reset position to beginning of track.

<img width="51" alt="Screen Shot 2020-04-23 at 5 35 38 PM" src="https://user-images.githubusercontent.com/9157833/80151975-dd1e0500-8588-11ea-8261-1bedfd1183ea.png">

Then, as you resize the page it should transition from the minimal layout to the regular layout.

**Comment by lhz516** [comment]
I think you can already hide everything except the play button. I agree that the player width shouldn't be capped to 300px. 

I'll remove the `min-width` in next patch. A temporary solution for now is to overwrite the container's `min-width` to `unset`.

The second request is too specific. It's changing the entire logic of current play/pause button. I'd suggest you to build an extra component outside the player component. The new component can use the audio object from the player's `ref`, so that you can play/pause, set currentTime for the audio outside.

**Comment by JeffreyCA** [comment]
Thanks for the reply. I can understand it's too specific.

My workaround solution:

I ended up using CSS @media queries to hide everything except for play/stop button. Then I overrode onPause to reset currentTime to the beginning if it is showing the minimal style (screen width is small enough). Lastly, I render a pause/stop icon using customIcons depending on the screen width.

**Comment by lhz516** [comment]
Removed `min-width: 300px` in `3.0.6`. Closing it
