### ISSUE TITLE
Total time increases by 1 second after dragging knob to end

### ISSUE THREAD

**Issue by JeffreyCA** [lhz516/react-h5-audio-player#38]
**Describe the bug**
While music is stopped or playing, drag knob to the end. The total time increases by 1 second.
I was able to reproduce this issue on https://hanzluo.com/#music.

Browser and its version: Chrome 83.0.4103.23
OS and its version: macOS 10.15.5 Beta (19F62f)

![gif](https://user-images.githubusercontent.com/9157833/80247182-9dfcbc00-863b-11ea-9b38-ac41763bd77f.gif)

**Comment by lhz516** [comment]
Good catch! I'll take a look

**Comment by lhz516** [comment]
You actually found a bug of Chrome's audio object. I logged the weird behavior:

![image](https://user-images.githubusercontent.com/9879279/80287480-c7265680-86e6-11ea-9aed-ce880da1172f.png)

1. Playing current audio
2. Drag progress to the end, but the duration increases half second. It only happens when manually set `audio.currentTime`.
3. Continue playing to the end of the new duration
4. Triggers `onEnd`, Jump to next song

 The step 2 is totally unexpected, I tested in Firefox and Edge, and they don't have this issue.

I'm considering to cache the `audio.duration` for the same `src`. However, even if we lock the display duration, when we drag progress to the end, it still goes step 3 internally which means the currentTime will be greater than duration. These side-effects need to be handled properly. I'm still thinking about the best solution. Let me know if you have any thoughts.

**Comment by JeffreyCA** [comment]
That's strange, it might be due to how Chrome estimates the track length. Perhaps it update its estimation when you seek to the end of the file.

Which one is the correct duration? On Safari I'm seeing two different times:
<img width="385" alt="Screen Shot 2020-04-25 at 3 29 16 PM" src="https://user-images.githubusercontent.com/9157833/80288998-ae7b6800-8709-11ea-9e9b-2c6b3de54741.png">

**Comment by lhz516** [comment]
The one on the player is based on `audio.duration`.
The one on the playlist is hardcoded.

It seems like Safari has one more second for the same audio's duration.

I used hardcoded duration because I want all audios' durations to be displayed when it's initially rendered.

**Comment by lhz516** [comment]
Closing since it's a browser issue.

Feel free to continue the discussion if anyone has any insights.
