### ISSUE TITLE
Custom step value for forward/backward jump.

### ISSUE THREAD

**Issue by bleuarg** [lhz516/react-h5-audio-player#40]
Hi, first of all thanks for you work on that component!

I have a use case where I want the skip forward and skip backward button to jump a different amount of time (as in some podcast players). 

ex: forward 30 sec and backward 10 sec.

I was thinking something like [that](https://github.com/bleuarg/react-h5-audio-player/commit/e9f57e3822422a476d8338d484d16d7fb291b794). I would be happy to submit a PR if that is something you are willing to add.

**Comment by lhz516** [comment]
Hi, I like your suggestion, if you are making a PR, I'd prefer to use one prop `progressJumpSteps` which can be an array of two numbers (backward/forward steps) - defaults to `[5000, 5000]`

In `3.x`, we should keep both `progressJumpStep` and `progressJumpSteps` (no breaking change); and in next major version `4`, we deprecate the old one. 

Thus we can use a single prop `progressJumpSteps` instead of the three you are proposing in your fork. What do you think?

**Comment by bleuarg** [comment]
Yeah good idea for the transition for the breaking change, I would think maybe with a more explicit declaration like so?

```
progressJumpSteps: {
  forward: 5000,
  backward: 5000
}
```
Or something along these lines, I find it a bit more user friendly to have the intent of the value clearly stated in the declaration.

Let me know and I can get a PR going!

**Comment by lhz516** [comment]
I make it an array because it has exactly 2 elements and no need to be extendable in the future.

I'm actually ok with either way, just go ahead and make it an object.

I've assigned to you. thanks for the help!

**Comment by lhz516** [comment]
Published 3.1.0. Closing

Thanks for the PR @bleuarg
