### ISSUE TITLE
The player is unable to play wav files with 13kbps bitrate

### ISSUE THREAD

**Issue by jcvegan** [lhz516/react-h5-audio-player#77]
I am trying to listen to wav files with 13 kbps of bitrate., But it never starts playing.

Package version: 3.4.1
React version: 16.13.1
Browser and its version: Chrome 86.0.4240.198
OS and its version: Windows 10 Build 19042.572

**Comment by lhz516** [comment]
This player is based on `<audio>` tag. Could you confirm if a pure `<audio>` tag can play your file?

**Comment by alaaeddin-imtilak** [comment]
> This player is based on `<audio>` tag. Could you confirm if a pure `<audio>` tag can play your file?

Hello,

Nope it's not based on <audio> because he's talking about wav49 .WAV no .wav and I am facing the same problem and trying to solve it but still no luck, I don't want to use online converter because it doesn't help me in my case I need something that solve the issue behind the scene I mean, programming solution or something like this.

**Comment by lhz516** [comment]
@alaaeddin-imtilak I don't quite get that. Could you clarify that if you are able to use a plain `<audio>` tag to play wav49 format?
