### ISSUE TITLE
Is there a way to change playback speed?

### ISSUE THREAD

**Issue by azeemakhter-arbisoft** [lhz516/react-h5-audio-player#81]
I just want to a feature in media player which allow us to change the playback speed on audio.
Is it already implemented in react-h5-audio-player?
Thanks.

**Comment by lhz516** [comment]
We don't want to include "change playback speed" in the library because this feature has quite different UI/UX in different applications.

You can implement your own change playback speed button using `customAdditionalControls` prop.

https://static.hanzluo.com/react-h5-audio-player-storybook/index.html?path=/docs/layouts-advanced--custom-additional-controls

**Comment by Arash-coder** [comment]
I tried so much but i can't change the playback speed rate. can you say how it works?

**Comment by lhz516** [comment]
@Arash-coder When you get the audio `ref`, just do `audio.current.playbackRate = 0.5; ` to make it slower.

Check [README](https://github.com/lhz516/react-h5-audio-player#advanced-usage) for how to get `ref`

**Comment by Arash-coder** [comment]
thank you :)
